/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package productionserver;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mike
 */
public class ServerLauncher extends javax.swing.JFrame implements ActionListener{

    private ProductionServer server;
    private Properties serverInfo = null;
    /**
     * Creates new form ServerLauncher
     */
    public ServerLauncher() {
        initComponents();
        serverInfo = new Properties();
        File serverInfoFile = new File(System.getProperty("user.dir")
                                     + System.getProperty("file.separator")
                                     + "servProdInfo");
        if (serverInfoFile.exists()) {
            try {
                serverInfo.load(new FileInputStream(serverInfoFile));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ServerLauncher.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ServerLauncher.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            serverInfo.setProperty("serverPort", "50000");
            try {
                serverInfo.store(new FileOutputStream(serverInfoFile), "Production server informations");
            } catch (IOException ex) {
                Logger.getLogger(ServerLauncher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        setLocationByPlatform(true);
        startButton.addActionListener(this);
        StopButton.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(startButton) && server == null) {
            server = new ProductionServer(Integer.parseInt(serverInfo.getProperty("serverPort")));
            server.start();
            serverStateLabel.setText("State: Running");
        }
        if (e.getSource().equals(StopButton) && server !=  null) {
            server.terminate();
            server = null;
            serverStateLabel.setText("State: Stopped");
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        serverStateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setText("Start");

        StopButton.setText("Stop");

        serverStateLabel.setText("State: Stopped");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverStateLabel)
                    .addComponent(StopButton)
                    .addComponent(startButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(serverStateLabel)
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addGap(33, 33, 33)
                .addComponent(StopButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerLauncher().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StopButton;
    private javax.swing.JLabel serverStateLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables


}
