/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduleProduction;

import bddDataObjects.Client;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.util.Date;

import javax.swing.DefaultComboBoxModel;

import bddDataObjects.Order;
import bddDataObjects.PartsType;
import java.util.Hashtable;
import java.util.Map;


/**
 *
 * @author mike
 */
public class OrderingWindow extends javax.swing.JFrame implements ActionListener{

    private PipedOutputStream posWindow;
    ThreadWorking threadWorking;
    ThreadStore threadStore;
    ThreadOrder threadOrder;
    Map<String, Client> ClientsList;
    
    public OrderingWindow() {
        initComponents();
        ClientsList = new Hashtable<String, Client>();
        orderButton.addActionListener(this);
        quitButton.addActionListener(this);
        comboBoxType.setModel(new DefaultComboBoxModel(PartsType.values()));
        
        PipedInputStream pisWorking, pisStore, pisOrder;
        PipedOutputStream posWorking, posOrder;
        
        try{
            pisWorking = new PipedInputStream();
            pisStore = new PipedInputStream();
            pisOrder = new PipedInputStream();
            posOrder = new PipedOutputStream(pisWorking);
            posWorking = new PipedOutputStream(pisStore);
            posWindow = new PipedOutputStream(pisOrder);
            
            threadOrder = new ThreadOrder(pisOrder, posOrder);
            threadWorking = new ThreadWorking(pisWorking, posWorking);
            threadStore = new ThreadStore(pisStore);
            threadOrder.start();
            threadWorking.start();
            threadStore.start();
        }
        catch (IOException e){
            
        }
        
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(quitButton)){
            
            
            
            threadWorking.terminate();
            threadStore.terminate();
            threadOrder.terminate();
            
            
            this.dispose();
        }
        else if(e.getSource().equals(orderButton)){
            try{
                ObjectOutputStream oos = new ObjectOutputStream(posWindow);
                if(!ClientsList.containsKey(textFieldClientName.getText())){
                    Client newClient = new Client(textFieldClientName.getText());
                    ClientsList.put(newClient.getName(), newClient);
                }
                
                oos.writeObject(new Order(new Date(), ClientsList.get(textFieldClientName.getText()).getId(),
                        (PartsType)comboBoxType.getSelectedItem(), Integer.parseInt(textFieldQuantity.getText())));
                System.out.println("A new order has been sent");
            }
            catch (IOException ioe){
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelClientName = new javax.swing.JLabel();
        labelPartType = new javax.swing.JLabel();
        labelQuantity = new javax.swing.JLabel();
        textFieldClientName = new javax.swing.JTextField();
        comboBoxType = new javax.swing.JComboBox();
        textFieldQuantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelClientName.setText("Client name");

        labelPartType.setText("Part type");

        labelQuantity.setText("Quantity");

        textFieldClientName.setText("Your name");

        comboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textFieldQuantity.setText("1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("MetalBuilding : Order metal parts");

        orderButton.setText("Order");

        quitButton.setText("Quit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelClientName)
                                    .addComponent(labelPartType)
                                    .addComponent(labelQuantity))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldClientName, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(comboBoxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(202, 202, 202))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClientName)
                    .addComponent(textFieldClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPartType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantity)
                    .addComponent(textFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderButton)
                    .addComponent(quitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OrderingWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelClientName;
    private javax.swing.JLabel labelPartType;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JTextField textFieldClientName;
    private javax.swing.JTextField textFieldQuantity;
    // End of variables declaration//GEN-END:variables


}
